In [ ]:
#Question 1 (55 marks)
#The Northwind data set, provided in XML format on Moodle, includes details of employees, customers,
#products and sales for a fictitious company.
#(a) Create a function to import this XML file. Your function must include appropriate exception
#handling clauses covering all possible error conditions and should return the parsed contents of the
#XML file.

In [124]:
#import xml.etree.ElementTree as ET
import xml.etree.ElementTree as ET
# build import_xml function
def import_xml(xml):
    #adding exception
    try:
        tree = ET.parse(xml)
        xml_root = tree.getroot()
        return xml_root
    except FileNotFoundError:
    #file open error
        print('Can not find the file {}'.format(xml))
    

xml_data = import_xml('NorthWind.xml')

In [123]:
# ET.tostring function print it out have look
print(ET.tostring(xml_data, encoding='utf8').decode('utf8'))

<?xml version='1.0' encoding='utf8'?>
<northwind>
	<Orders>
		<Order OrderID="10248">
			<CustomerID>VINET</CustomerID>
			<EmployeeID>5</EmployeeID>
			<OrderDate>1996-07-04T14:25:55</OrderDate>
			<RequiredDate>1996-08-01T06:43:44</RequiredDate>
			<ShippedDate>1996-07-16T04:00:12</ShippedDate>
			<ShipVia>3</ShipVia>
			<Freight>32.3800</Freight>
			<ShipName>Vins et alcools Chevalier</ShipName>
			<ShipAddress>59 rue de l'Abbaye</ShipAddress>
			<ShipCity>Reims</ShipCity>
			<ShipRegion />
			<ShipPostalCode>51100</ShipPostalCode>
			<ShipCountry>France</ShipCountry>
			<OrderDetails>
				<OrderDetail>
					<ProductID>11</ProductID>
					<UnitPrice>14.0000</UnitPrice>
					<Quantity>12</Quantity>
					<Discount>0</Discount>
				</OrderDetail>
				<OrderDetail>
					<ProductID>42</ProductID>
					<UnitPrice>9.8000</UnitPrice>
					<Quantity>10</Quantity>
					<Discount>0</Discount>
				</OrderDetail>
				<OrderDetail>
					<ProductID>72</ProductID>
					<UnitPrice>34.8000</UnitPrice

In [ ]:
#(b) Using the function you created in a) above, load the XML file. Then use the print() function to
#display the ProductName and UnitPrice for the second, fourth, sixth, eighth and tenth products.
#Hint: the range() function might come in useful here!

In [259]:
# Using the function I created
xml_data = import_xml('NorthWind.xml')

def find_product(data):
    # Using for loop to find product area
    for i in range(0,len(data)):
        # if the tag show product then do next for loop
        if data[i].tag == "Products":
            # Look into product section to find ProductName and UnitPrice for 2 4 6 8 10 products
            for j in range(0,10,2):
                find_PName = data[i][j].find('ProductName').text
                find_Uprice = data[i][j].find('UnitPrice').text
                print("Product name: {}  Unit price: {}".format(find_PName, find_Uprice))
        

find_product(xml_data)    

Product name: Chai  Unit price: 18.0000
Product name: Aniseed Syrup  Unit price: 10.0000
Product name: Chef Anton's Gumbo Mix  Unit price: 21.3500
Product name: Uncle Bob's Organic Dried Pears  Unit price: 30.0000
Product name: Mishi Kobe Niku  Unit price: 97.0000


In [ ]:
#(c) Extract all the following fields or attributes for all customers who live in Mexico and save them to a
#CSV file:
#• CustomerID
#• CompanyName
#• ContactName
#• City
#• PostalCode
#Your code should contain appropriate exception handling clauses and the exported CSV file should
#contain the column names.

In [255]:
# I try to find the customers data but can't finish put in csv )
for i in range(0,len(xml_data)):
    if xml_data[i].tag == "Customers":
        for j in range(0,len(xml_data[i])):
            for k in range(0,len(xml_data[i][j])):
                print(xml_data[i][j][k].text)


Alfreds Futterkiste
Maria Anders
Sales Representative
Obere Str. 57
Berlin
None
12209
Germany
030-0074321
030-0076545
Ana Trujillo Emparedados y helados
Ana Trujillo
Owner
Avda. de la Constitución 2222
México D.F.
None
05021
Mexico
(5) 555-4729
(5) 555-3745
Antonio Moreno Taquería
Antonio Moreno
Owner
Mataderos  2312
México D.F.
None
05023
Mexico
(5) 555-3932
None
Around the Horn
Thomas Hardy
Sales Representative
120 Hanover Sq.
London
None
WA1 1DP
UK
(171) 555-7788
(171) 555-6750
Berglunds snabbköp
Christina Berglund
Order Administrator
Berguvsvägen  8
Luleå
None
S-958 22
Sweden
0921-12 34 65
0921-12 34 67
Blauer See Delikatessen
Hanna Moos
Sales Representative
Forsterstr. 57
Mannheim
None
68306
Germany
0621-08460
0621-08924
Blondesddsl père et fils
Frédérique Citeaux
Marketing Manager
24, place Kléber
Strasbourg
None
67000
France
88.60.15.31
88.60.15.32
Bólido Comidas preparadas
Martín Sommer
Owner
C/ Araquil, 67
Madrid
None
28023
Spain
(91) 555 22 82
(91) 555 91 99
Bon app'
Laurence

TypeError: find() missing required argument 'path' (pos 1)

In [ ]:
#Question 2 (25 marks)
#(a) Create a NumPy ndarray containing all even numbers between 200 and 799. [5 marks]


In [47]:
# import numpy
import numpy as np
# Create a NumPy ndarray even numbers between 200 and 799
my_ndarray = np.arange(200,799,2)
print(my_ndarray)

[200 202 204 206 208 210 212 214 216 218 220 222 224 226 228 230 232 234
 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264 266 268 270
 272 274 276 278 280 282 284 286 288 290 292 294 296 298 300 302 304 306
 308 310 312 314 316 318 320 322 324 326 328 330 332 334 336 338 340 342
 344 346 348 350 352 354 356 358 360 362 364 366 368 370 372 374 376 378
 380 382 384 386 388 390 392 394 396 398 400 402 404 406 408 410 412 414
 416 418 420 422 424 426 428 430 432 434 436 438 440 442 444 446 448 450
 452 454 456 458 460 462 464 466 468 470 472 474 476 478 480 482 484 486
 488 490 492 494 496 498 500 502 504 506 508 510 512 514 516 518 520 522
 524 526 528 530 532 534 536 538 540 542 544 546 548 550 552 554 556 558
 560 562 564 566 568 570 572 574 576 578 580 582 584 586 588 590 592 594
 596 598 600 602 604 606 608 610 612 614 616 618 620 622 624 626 628 630
 632 634 636 638 640 642 644 646 648 650 652 654 656 658 660 662 664 666
 668 670 672 674 676 678 680 682 684 686 688 690 69

In [ ]:
#(b) Modify the array so that it becomes a 2-D array containing 25 rows and 12 columns.

In [48]:
# reshape array to 25 rows and 12 columns
my_ndarray = my_ndarray.reshape(25,12)
print(array_2D)

[[200 202 204 206 208 210 212 214 216 218 220 222]
 [224 226 228 230 232 234 236 238 240 242 244 246]
 [248 250 252 254 256 258 260 262 264 266 268 270]
 [272 274 276 278 280 282 284 286 288 290 292 294]
 [296 298 300 302 304 306 308 310 312 314 316 318]
 [320 322 324 326 328 330 332 334 336 338 340 342]
 [344 346 348 350 352 354 356 358 360 362 364 366]
 [368 370 372 374 376 378 380 382 384 386 388 390]
 [392 394 396 398 400 402 404 406 408 410 412 414]
 [416 418 420 422 424 426 428 430 432 434 436 438]
 [440 442 444 446 448 450 452 454 456 458 460 462]
 [464 466 468 470 472 474 476 478 480 482 484 486]
 [488 490 492 494 496 498 500 502 504 506 508 510]
 [512 514 516 518 520 522 524 526 528 530 532 534]
 [536 538 540 542 544 546 548 550 552 554 556 558]
 [560 562 564 566 568 570 572 574 576 578 580 582]
 [584 586 588 590 592 594 596 598 600 602 604 606]
 [608 610 612 614 616 618 620 622 624 626 628 630]
 [632 634 636 638 640 642 644 646 648 650 652 654]
 [656 658 660 662 664 666 668 6

In [ ]:
#(c) Using indexing and slicing, select all data from the third and fourth columns

In [51]:
# select the third and fourth columns
slicing_data=my_ndarray[:,2:4]
print(slicing_data)

array([[204, 206],
       [228, 230],
       [252, 254],
       [276, 278],
       [300, 302],
       [324, 326],
       [348, 350],
       [372, 374],
       [396, 398],
       [420, 422],
       [444, 446],
       [468, 470],
       [492, 494],
       [516, 518],
       [540, 542],
       [564, 566],
       [588, 590],
       [612, 614],
       [636, 638],
       [660, 662],
       [684, 686],
       [708, 710],
       [732, 734],
       [756, 758],
       [780, 782]])

In [ ]:
#(d) Using an appropriate function, split the array into 4 arrays column-wise.

In [57]:
#split the array into 4 arrays column-wise
cw_array = np.hsplit(my_ndarray,4)
print(cw_array)

[array([[200, 202, 204],
       [224, 226, 228],
       [248, 250, 252],
       [272, 274, 276],
       [296, 298, 300],
       [320, 322, 324],
       [344, 346, 348],
       [368, 370, 372],
       [392, 394, 396],
       [416, 418, 420],
       [440, 442, 444],
       [464, 466, 468],
       [488, 490, 492],
       [512, 514, 516],
       [536, 538, 540],
       [560, 562, 564],
       [584, 586, 588],
       [608, 610, 612],
       [632, 634, 636],
       [656, 658, 660],
       [680, 682, 684],
       [704, 706, 708],
       [728, 730, 732],
       [752, 754, 756],
       [776, 778, 780]]), array([[206, 208, 210],
       [230, 232, 234],
       [254, 256, 258],
       [278, 280, 282],
       [302, 304, 306],
       [326, 328, 330],
       [350, 352, 354],
       [374, 376, 378],
       [398, 400, 402],
       [422, 424, 426],
       [446, 448, 450],
       [470, 472, 474],
       [494, 496, 498],
       [518, 520, 522],
       [542, 544, 546],
       [566, 568, 570],
       [590, 

In [ ]:
#(e) On the first of the split arrays, sum up the row values for the 1st and 3rd columns

In [58]:
#sum up the row values 1st and 3rd columns
print(my_ndarray[:,0] + my_ndarray[:,2])

[ 404  452  500  548  596  644  692  740  788  836  884  932  980 1028
 1076 1124 1172 1220 1268 1316 1364 1412 1460 1508 1556]


In [ ]:
#Question 3 (20 marks)
#Given the following string:
#"""
#Betty Botter bought some butter
#But she said the butter’s bitter
#If I put it in my batter, it will make my batter bitter
#But a bit of better butter will make my batter better
#So ‘twas better Betty Botter bought a bit of better butter
#"""
#(a) Using regular expressions, write a single function to highlight the words “batter” and “bitter” if
#they appear anywhere in a line. [10 marks]
#The text produced by your code look like this:
#Betty Botter bought some butter
#But she said the butter’s {bitter}
#If I put it in my {batter}, it will make my {batter} {bitter}
#But a bit of better butter will make my {batter} better
#So ‘twas better Betty Botter bought a bit of better butter
#"""

In [96]:
## import regular expressions
import re

data_string = '''
Betty Botter bought some butter
But she said the butter’s bitter
If I put it in my batter, it will make my batter bitter
But a bit of better butter will make my batter better
So ‘twas better Betty Botter bought a bit of better butter
'''
# creat function find words
def find_words(key_words, data):
    
    # re.M to match line wise
    #re.sub search and replace
    # \g<N> capture group   
    print(re.compile(key_words, re.M).sub("{\g<0>}", string.rstrip()))



#use this function to get string batter|bitter
find_words(r"batter|bitter",data_string)


Betty Botter bought some butter
But she said the butter’s {bitter}
If I put it in my {batter}, it will make my {batter} {bitter}
But a bit of better butter will make my {batter} better
So ‘twas better Betty Botter bought a bit of better butter


In [62]:
#(b) Write a function that uses regular expressions to extract all the numeric digits and returns them as a
#list.

In [100]:
# import regular expressions
import re

# creat digit in string
test_string2 = '''
Betty Botter bought some butter 232132 fdsgd 3123123
'''
# creat function find digit and return list
def find_digit(data):
    # empty list
    digit_list = []
    # append found digit in list
    digit_list.append(re.findall(r"\d+",data))
    return digit_list

# use function find digit
find_digit(test_string2)

[['232132', '3123123']]